### ISSUE TITLE
Make `pip install palanteer` possible

### ISSUE THREAD

**Issue by meysam81** [dfeneyrou/palanteer#11]
Hello guys,

Thanks for your contribution. `palanteer` seems really cool. I have to give it a shot to see what it has to offer.

I am proposing that you would consider publishing your package in the [PyPi registry](pypi.org) so that python developers would be able to install it using `pip`.

Keep up the good work and stay awesome. 🥂

**Comment by dfeneyrou** [comment]
The fixed issue #8 is one step toward this goal. 
Wheel packages are now used internally, and are compatible with the format of the Pypi registry.

**Comment by dfeneyrou** [comment]
Palanteer Python packages are now available on Pypi registry:
 - on Windows as binary for Python 3.7, 3.8 and 3.9 (because not everybody has a configured MSVC on his Windows OS)
 - on Linux as sources (because too much distributions and everybody has a gcc on his Linux)

So the new installation commands are:
- ```pip install palanteer``` for the Python instrumentation package
-  ```pip install palanteer_scripting``` for the scripting module
