### ISSUE TITLE
Crash when trying to instrument a program on current git master

### ISSUE THREAD

**Issue by jcelerier** [dfeneyrou/palanteer#35]
Linux x64: as soon as I launch the app to profile, the GUI crashes with:

```
[PALANTEER] Assertion failed: _underRecordRecIdx>=0
  On function: void vwMain::draw()
  On file    : /home/jcelerier/projets/perso/lafajol/3rdparty/palanteer/server/viewer/vwMain.cpp(357)
    - int     _underRecordRecIdx   = -1

  #0  0x55AE269C7652 : _ZN6vwMain4drawEv
  #1  0x55AE26A59C37 : _ZN10vwPlatform6redrawEv
  #2  0x55AE26A59D29 : _ZN10vwPlatform3runEv
  #3  0x55AE26A5A80B : _Z11bsBootstrapiPPc
  #4  0x7F560497130C : __libc_start_call_main
  #5  0x7F56049713BD : __libc_start_main@@GLIBC_2.34
  #6  0x55AE269449D1 : _start
```

**Comment by jcelerier** [comment]
I have it with just the testprogram (rebuilt with -g):

```
$ ./testprogram collect     
Mode 'connected'
[PALANTEER] Assertion failed: _underRecordRecIdx>=0
  On function: void vwMain::draw()
  On file    : /home/jcelerier/projets/perso/lafajol/3rdparty/palanteer/server/viewer/vwMain.cpp(357)
    - int     _underRecordRecIdx   = -1

  #0  vwMain.cpp(357) : vwMain::draw()
  #1  vwPlatform.cpp(367) : vwPlatform::redraw()
  #2  vwPlatform.cpp(307) : vwPlatform::run()
  #3  vwPlatform.cpp(198) : bsBootstrap(int, char**)
  #4  0x7FF5D1DDD30C : __libc_start_call_main
  #5  0x7FF5D1DDD3BD : __libc_start_main@@GLIBC_2.34
  #6  0x55B0763BE5B1 : _start
```

**Comment by dfeneyrou** [comment]
Thanks for your report!

The crash occurs because the GUI cannot find the record file which is currently live.
I have no idea of the root cause of this internal automata issue, the previous commit is not a fix, it just disconnects from the app instead of asserting in this case, which allows to read some information inside the console window (whose access was prevented by the assertion...)

So if you have some time, I am interested in the last lines of the console window, and and also in the terminal output with this instrumentation patch:

```
diff --git a/server/viewer/vwMain.cpp b/server/viewer/vwMain.cpp
index 72504c1..0d681e2 100644
--- a/server/viewer/vwMain.cpp
+++ b/server/viewer/vwMain.cpp
@@ -926,7 +926,9 @@ vwMain::findRecord(const bsString& recordPath, int& foundAppIdx, int& foundRecId
         const AppRecordInfos& appElem = _cmRecordInfos[appIdx];
         for(int recIdx=0; recIdx<appElem.records.size(); ++recIdx) {
             const RecordInfos& recElem = appElem.records[recIdx];
+            printf("Comparing [%s] and [%s]\n", recElem.path.toChar(), recordPath.toChar());
             if(recElem.path!=recordPath) continue;
+            printf("   Found!\n");
             foundAppIdx = appIdx;  // Record was found
             foundRecIdx = recIdx;
             return true;
```
It prints the path of the current record and its comparison with the ones in the catalog (the new one under recording should be inside by design, that is why I do not understand the root cause)

**Comment by jcelerier** [comment]
I tried adding the printfs and it didn't log anything to the console ; when putting a breakpoint on vwMain::findRecord it seemsthat it doesn't even enter the loop:

```

Thread 1 "palanteer" hit Breakpoint 1, vwMain::findRecord (this=0x555555cd6f00, recordPath=..., foundAppIdx=@0x555555cd7578: -1, foundRecIdx=@0x555555cd757c: -1) at palanteer/server/viewer/vwMain.cpp:923
923	    foundAppIdx = -1;
(gdb) n
924	    foundRecIdx = -1;
(gdb) n
100	    int  size(void)     const { return _size; }
(gdb) n
vwMain::draw (this=0x555555cd6f00) at palanteer/server/viewer/vwMain.cpp:356
356	        if(_underRecordRecIdx==-1) {
(gdb) n
357	            logToConsole(LOG_ERROR, "BUG: file %s (current record) not found...\n", (*recordPtr)->recordPath.toChar());
(gdb) 
```

The console log looks like: 

BUG: file /home/jcelerier/.palanteer/records/C++ example/rec_2022-03-20_18h31m57s.plt (current record) not found...

but I do have the file: 

```
$ ls -lah '/home/jcelerier/.palanteer/records/C++ example/rec_2022-03-20_18h31m57s.plt' 
-rw-r--r-- 1 jcelerier users 416 20 mars  18:34 '/home/jcelerier/.palanteer/records/C++ example/rec_2022-03-20_18h31m57s.plt'
```

**Comment by dfeneyrou** [comment]
Thanks for your quick answer!
This means that the issue is located inside the ```vwMain::updateRecordList``` (just abovet he ```findRecord``` one) function which is supposed to collect all the present records.  I suppose that the list of present records is empty, hence the absence of terminal output and thus match with the current one.
In commit #00b6d729ab408e994344d3ad5c679ae864fcce56 , additional logs are added when building this list of applications and records. The console logs should provide more information on the issue when parsing the directory content (your path seems ok, nothing weird there...)

**Comment by jcelerier** [comment]
okay, pulling and testing :)

**Comment by jcelerier** [comment]
hmmm I don't see much more logs :(

![hmm](https://user-images.githubusercontent.com/2772730/159282801-a870a6df-0aa1-47b9-9f6b-17b17536af39.png)

**Comment by dfeneyrou** [comment]
This issue is really intriguing, no console output means no error when calling the dirent API to get the content of a directory.
May I ask you to try with the attached patch which adds some console log for each steps when trying to build the catalog of records?
[issue35_debugpatch1.txt](https://github.com/dfeneyrou/palanteer/files/8319116/issue35_debugpatch1.txt)
It looks like a low level issue when getting a file list, but I really do not understand what is special in your environment. I double-checked the code for the OS abstraction (the server/base/bsOsLinux.cpp file) but saw nothing obvious...

**Comment by jcelerier** [comment]
![that](https://user-images.githubusercontent.com/2772730/159363015-d1c5c71c-d20d-459a-88f1-1096961fab23.png)

here's the console output with that patch ^

As for the environment, I'm running a standard archlinux distro.. maybe you can try it with docker ? (making X11 work is always kinda hard though)

**Comment by jcelerier** [comment]
```
$ cd ~/.palanteer
$  tree
.
├── configs
│   ├── app_C++ example.cfg
│   └── palanteer.cfg
└── records
    ├── C++ example
    │   ├── rec_2022-03-15_20h05m41s.plt
    │   ├── rec_2022-03-20_18h30m43s.plt
    │   ├── rec_2022-03-20_18h31m04s.plt
    │   ├── rec_2022-03-20_18h31m57s.plt
    │   ├── rec_2022-03-21_15h28m30s.plt
    │   ├── rec_2022-03-21_15h33m02s.plt
    │   ├── rec_2022-03-21_15h37m41s.plt
    │   └── rec_2022-03-21_22h00m03s.plt
    └── my program name
        ├── rec_2022-03-15_19h51m16s.plt
        ├── rec_2022-03-15_19h51m30s.plt
        ├── rec_2022-03-15_19h53m31s.plt
        └── rec_2022-03-15_20h05m11s.plt

4 directories, 14 files

```

**Comment by jcelerier** [comment]
ah, I think I know :)

in 

    bsDirStatusCode osGetDirContent(const bsString& path, bsVec<bsDirEntry>& entries)

the subfolders are listed as DT_UNKNOWN, not DT_DIR. This must be this issue:

https://stackoverflow.com/questions/23958040/checking-if-a-dir-entry-returned-by-readdir-is-a-directory-link-or-file-dent/29094555#29094555

**Comment by dfeneyrou** [comment]
Thanks a lot for the investigation! If you can confirm that the fix is working, that would be great!

**Comment by jcelerier** [comment]
yes, it's working, thanks :)
