### ISSUE TITLE
Python multiprocessing support

### ISSUE THREAD

**Issue by danielhrisca** [dfeneyrou/palanteer#36]
Hello,

I've traced a Python application that uses multiprocessing. The way the processes are started is like this:

- main process running a PySide6 GUI
    - secondary process started from the main process
        - after some user configuration the secondary process starts several child processes

I can only see the `main` process trace information.

Is there something that I'm missing?

**Comment by dfeneyrou** [comment]
Sorry for late answer...
To enable profiling, the minimum actions that shall occur in any python program/process is to import the module `palanteer` and call the function `plInitAndStart` (among other things, this installs the hooks required to track the functions calls).

If your program creates other processes (with calls to subprocess or system calls), the enabled state of the profiling is not automatically propagated to them because they are independent executables. They even can be made with any language, be a shell script, a binary, ...

So propagating the profiling enabled state to child processes cannot be done (IMHO) automatically and requires some dedicated code in each parent python program.
For instance, if `palanteer._is_activated ` is `True` (an additional getter in the API is indeed needed...):

- Add the following prefix to your subprocess call args : [ "python3", "-m", "palanteer" ]
- Manually provide a command line option to your child program which trigs the import the module `palanteer` and call the function `plInitAndStart`
