### ISSUE TITLE
"make install" doesn't work

### ISSUE THREAD

**Issue by mortymacs** [dfeneyrou/palanteer#8]
It needs to support `make install` to install Palanteer globally on a system.

**Comment by dfeneyrou** [comment]
Indeed, there is no such target currently.
Examples put aside, there are 3 "installable" components: the viewer and the 2 Python modules. The Python module can be installed for the user only or in the system (with administrator rights, this shall be currently done manually as explained in the README.md of these folders).

Currently, "make"  builds the viewer and installs Python module for the user.
I tend to say that "make" can stay as now, and "make install" shall:
  - On Linux, copiy the viewer in /usr/local/bin (as a default prefix) and install the Python modules for all users (requires root rights)
  - On Windows, just installs the Python modules for all users (requires administator rights)

What is your view on these expected behavior of "make" and "make install" for both OS?

**Comment by mortymacs** [comment]
As I wanted to prepare an ArchLinux package, I wanted to use `make install` if exists. But now as you explained I can follow your approach to make the installation package :+1: 
Thanks!

**Comment by dfeneyrou** [comment]
The make target "install" has been added.

The behavior is now the following:
 - "make" now builds the viewer, the C++ example and the 2 python packages (wheel). The "wheels" are not installed.
 - "make install" builds as above, if needed, and installs the 2 "wheels" (with pip install)
   - if root/administrator, the installation is done for all users (pip behavior)
   - else the installation of the 2 packages are only for the current user. 

Only python packages are installed, as the viewer is a standalone binary so easy to "install" manually

**Comment by mortymacs** [comment]
The AUR package is ready: https://aur.archlinux.org/packages/palanteer/

**Comment by dfeneyrou** [comment]
Thanks @mortymacs!
Unfortunately, I do not use Arch Linux (Debian) so I cannot test it.
I also do not know how the selection of the packages to AUR-ify is done, but I appreciate :-)

I noticed that there is only 1 python package (the python instrumentation one, named "palanteer"), the scripting module (named "palanteer_scripting") has no corresponding "pip install" call.
Is it expected or is it a limitation of the installation (which references the ${pkgname}, and for this second package, the name is different, or need a suffix "_scripting")?

Also is there an action to do when a new release is published?

**Comment by mortymacs** [comment]
Hi @dfeneyrou  :)

Thank you and thanks for mentioning the issue on the package. I just fixed it :+1: now, it contains 2 Python packages.

About the new releases, I just enabled the notification "on Release" in this repository to notify me.
Yesterday, I had a call with a friend of mine, we're going to make a pipeline to publish some open source packages for popular GNU/Linux distributions (Debian/Ubuntu, Redhat/Fedora, and ArchLinux/Manjaro atm) in public. My all AUR packages will be in the pipeline to automatically build and publish in our servers. So, Palanteer will be one of them.
I'll keep you in touch as soon as we could release the first version of the pipeline.
